### ISSUE TITLE
Bundler gem load error

### ISSUE THREAD

**Issue by faun** [wildbit/postmark-gem#70]
When loading the postmark gem in rake task, sometimes I see the following error & stacktrace:

```
Bundler::GemRequireError: There was an error while trying to load the gem 'postmark-rails'.
Gem Load Error is: wrong argument type Regexp (expected String)

...

TypeError: wrong argument type Regexp (expected String)
  from active_support/dependencies.rb:292:in `require'
  from active_support/dependencies.rb:292:in `block in require'
  from active_support/dependencies.rb:258:in `load_dependency'
  from active_support/dependencies.rb:292:in `require'
  from postmark.rb:13:in `<top (required)>'
  from active_support/dependencies.rb:292:in `require'
  from active_support/dependencies.rb:292:in `block in require'
  from active_support/dependencies.rb:258:in `load_dependency'
  from active_support/dependencies.rb:292:in `require'
  from postmark-rails.rb:3:in `<top (required)>'
  from bundler/runtime.rb:81:in `require'
  from bundler/runtime.rb:81:in `block (2 levels) in require'
  from bundler/runtime.rb:76:in `each'
  from bundler/runtime.rb:76:in `block in require'
  from bundler/runtime.rb:65:in `each'
  from bundler/runtime.rb:65:in `require'
  from bundler.rb:114:in `require'
  from config/application.rb:16:in `<top (required)>'
  from Rakefile:6:in `require'
  from Rakefile:6:in `<top (required)>'
  from rake/rake_module.rb:29:in `load'
  from rake/rake_module.rb:29:in `load_rakefile'
  from rake/application.rb:703:in `raw_load_rakefile'
  from rake/application.rb:104:in `block in load_rakefile'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:103:in `load_rakefile'
  from rake/application.rb:82:in `block in run'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:80:in `run'
  from vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
  from vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
  from vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
Bundler::GemRequireError: There was an error while trying to load the gem 'postmark-rails'.
Gem Load Error is: wrong argument type Regexp (expected String)
Backtrace for gem load error is:
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/app/src/vendor/bundle/ruby/2.5.0/gems/postmark-1.11.0/lib/postmark.rb:13:in `<top (required)>'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
/app/src/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
/app/src/vendor/bundle/ruby/2.5.0/gems/postmark-rails-0.16.0/lib/postmark-rails.rb:3:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.5/lib/bundler.rb:114:in `require'
/app/src/config/application.rb:16:in `<top (required)>'
/app/src/Rakefile:6:in `require'
/app/src/Rakefile:6:in `<top (required)>'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:82:in `block in run'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/app/src/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/app/src/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/app/src/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
Bundler Error Backtrace:

  from bundler/runtime.rb:84:in `rescue in block (2 levels) in require'
  from bundler/runtime.rb:80:in `block (2 levels) in require'
  from bundler/runtime.rb:76:in `each'
  from bundler/runtime.rb:76:in `block in require'
  from bundler/runtime.rb:65:in `each'
  from bundler/runtime.rb:65:in `require'
  from bundler.rb:114:in `require'
  from config/application.rb:16:in `<top (required)>'
  from Rakefile:6:in `require'
  from Rakefile:6:in `<top (required)>'
  from rake/rake_module.rb:29:in `load'
  from rake/rake_module.rb:29:in `load_rakefile'
  from rake/application.rb:703:in `raw_load_rakefile'
  from rake/application.rb:104:in `block in load_rakefile'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:103:in `load_rakefile'
  from rake/application.rb:82:in `block in run'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:80:in `run'
  from vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
  from vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
  from vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
```

Do you have any guidance for how to avoid this?

Thanks!

**Comment by temochka** [comment]
Hi @faun,

Sorry, no, I’ve never encountered this. If this is still a problem, could you please reopen and share some more details about your environment? (Ruby version, Rails or ActionMailer (if using), etc.).

**Comment by faun** [comment]
I think this issue is more widespread, as I'm seeing issues with other gems now as well.
